spring.application.name=MealArchitect

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/meal_architect_db

spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Tell Hibernate exactly which SQL dialect to use
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH_ISSUER_URI}

logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
